IVERILOG ?= iverilog
VVP ?= vvp
BUILD_DIR ?= /tmp/snestang-sdram-gsu
SOURCES := ../sdram_cl2_3ch_gsu.v tb_sdram_gsu_shared.sv
TESTS := $(foreach bank,4 8,$(foreach bs,0 1,$(foreach rom,0 1,$(BUILD_DIR)/bank$(bank)-bs$(bs)-rom$(rom))))
.PHONY: test
test: $(TESTS)
	@set -e; for test in $(TESTS); do $(VVP) $$test; done
$(BUILD_DIR)/bank4-bs%-rom0: $(SOURCES) Makefile.sdram_gsu
	mkdir -p $(BUILD_DIR)
	$(IVERILOG) -g2012 -Wall -Wno-timescale -DVERILATOR -DSDRAM_16M -s tb_sdram_gsu_shared -Ptb_sdram_gsu_shared.DONE_DELAY=$* -Ptb_sdram_gsu_shared.ROM_DELAY=0 -o $@ $(SOURCES)
$(BUILD_DIR)/bank4-bs%-rom1: $(SOURCES) Makefile.sdram_gsu
	mkdir -p $(BUILD_DIR)
	$(IVERILOG) -g2012 -Wall -Wno-timescale -DVERILATOR -DSDRAM_16M -s tb_sdram_gsu_shared -Ptb_sdram_gsu_shared.DONE_DELAY=$* -Ptb_sdram_gsu_shared.ROM_DELAY=1 -o $@ $(SOURCES)
$(BUILD_DIR)/bank8-bs%-rom0: $(SOURCES) Makefile.sdram_gsu
	mkdir -p $(BUILD_DIR)
	$(IVERILOG) -g2012 -Wall -Wno-timescale -DVERILATOR -s tb_sdram_gsu_shared -Ptb_sdram_gsu_shared.DONE_DELAY=$* -Ptb_sdram_gsu_shared.ROM_DELAY=0 -o $@ $(SOURCES)
$(BUILD_DIR)/bank8-bs%-rom1: $(SOURCES) Makefile.sdram_gsu
	mkdir -p $(BUILD_DIR)
	$(IVERILOG) -g2012 -Wall -Wno-timescale -DVERILATOR -s tb_sdram_gsu_shared -Ptb_sdram_gsu_shared.DONE_DELAY=$* -Ptb_sdram_gsu_shared.ROM_DELAY=1 -o $@ $(SOURCES)
